Fix for [#247] search bar not working when in /torrents endpoint
torrust/torrust-index-gui pull request #251
Opened 2023-09-02 21:02 UTC by mario-nt

Fixes #247 

The search bar was not working when in the /torrents endpoint, because the watcher listening for changes in the url path was not triggering when the user searches for a specific torrent.

2023-09-04 15:52 UTC, josecelano requested changes
Hi @mario-nt, It works, but we are making unnecessary requests.

![image](https://github.com/torrust/torrust-index-frontend/assets/58816/5963f7e1-c5c6-448a-9d55-ad1b939bd7eb)

The request to get the torrents is made four times.

2023-09-11 11:48 UTC, josecelano commented
ACK b90021705b03ee87a8d78cd29eeb11e96d6a6f25

2023-09-11 12:16 UTC, josecelano commented
Hi @mario-nt I've tested it, and it works. Tests are failing because the Tracker container image has changed, and we need to [update the docker-compose configuration as I'm doing on the Index Backend](https://github.com/torrust/torrust-index-backend/pull/270).

I've created a new issue: https://github.com/torrust/torrust-index-frontend/issues/262

I will finish that issue, then I will do the same here in this repo, and finally, we can re-run tests in this PR. If everything is OK I will merge it.

2023-09-11 12:17 UTC, josecelano commented
I clicked on `Close with a comment` instead of `Comment` :-(

2023-09-12 12:19 UTC, mario-nt commented
Rebase and tests OK, ready to be reviewed @josecelano .

2023-09-12 12:20 UTC, josecelano commented
ACK 6c727337ed8ec7f4e603c35d83e2d1d9be85c367

2023-09-12 12:21 UTC, merged